### ISSUE TITLE
Problem when using irb

### ISSUE THREAD

**Issue by fblundun** [fog/fog-aws#195]
Slightly strange error here. My file buckets.rb contains the following:

```
dir = s3.directories.get("my_bucket", "my_path")
```

where `s3.class` is `Fog::Storage::AWS::Real`.

If I run `ruby buckets.rb`, there is not problem. But if I run `irb buckets.rb`, I get an error:

```
Excon::Errors::Forbidden: Expected(200) <=> Actual(403 Forbidden)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>78C27CFCE0C716FA</RequestId><HostId>5gioIOKvzK3YApRjirQoNXpHHedmgNFCNWjMTYSXuyY7iFUuaEtr27sP/fYisQEhHLWvrFZ3HGk=</HostId></Error>"
  :headers       => {
    "Content-Type"     => "application/xml"
    "Date"             => "Fri, 30 Oct 2015 11:42:51 GMT"
    "Server"           => "AmazonS3"
    "x-amz-id-2"       => "5gioIOKvzK3YApRjirQoNXpHHedmgNFCNWjMTYSXuyY7iFUuaEtr27sP/fYisQEhHLWvrFZ3HGk="
    "x-amz-request-id" => "78C27CFCE0C716FA"
  }
  :local_address => "10.0.2.15"
  :local_port    => 40247
  :reason_phrase => "Forbidden"
  :remote_ip     => "54.231.141.161"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"

    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/expects.rb:9:in `response_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/response_parser.rb:8:in `response_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/connection.rb:372:in `response'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/connection.rb:236:in `request'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/connection.rb:256:in `request'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/connection.rb:256:in `request'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/excon-0.45.3/lib/excon/connection.rb:256:in `request'
... 6 levels...
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-1.24.0/lib/fog/aws/models/storage/directory.rb:35:in `location'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-core-1.31.1/lib/fog/formatador.rb:78:in `object_attributes'
    from org/jruby/RubyArray.java:2412:in `map'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-core-1.31.1/lib/fog/formatador.rb:77:in `object_attributes'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-core-1.31.1/lib/fog/formatador.rb:63:in `attribute_string'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-core-1.31.1/lib/fog/formatador.rb:53:in `object_string'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-core-1.31.1/lib/fog/formatador.rb:14:in `format'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/formatador-0.2.5/lib/formatador.rb:92:in `indent'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-core-1.31.1/lib/fog/formatador.rb:41:in `indent'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-core-1.31.1/lib/fog/formatador.rb:14:in `format'
    from /home/vagrant/.rvm/gems/jruby-1.7.19/gems/fog-core-1.31.1/lib/fog/core/model.rb:24:in `inspect'
    from org/jruby/RubyProc.java:271:in `call'
    from org/jruby/RubyKernel.java:1507:in `loop'
    from org/jruby/RubyKernel.java:1270:in `catch'
    from org/jruby/RubyKernel.java:1270:in `catch'
    from /home/vagrant/.rvm/rubies/jruby-1.7.19/bin/irb:13:in `(root)'jruby-1.7.19 :020 > 
```

I am using rvm. The error occurs with both JRuby and Ruby 2.2.1, but only when using irb. Does anybody have any idea what might be going wrong?

**Comment by lanej** [comment]
@fblundun i would verify that the client initialization code is correct.  My guess is that in one form the `~/.fog` file is being used for default credentials but not in the other.

**Comment by fblundun** [comment]
Some additional information:

This is my initialization code.

```ruby
        fog = Fog::Storage.new({
          :provider => 'AWS',
          :region => my_region,
          :aws_access_key_id => access_key_id,
          :aws_secret_access_key => secret_access_key
        })
        fog.sync_clock
        fog.directories.get("my_bucket", "my_path")
```

I am not using a `~/.fog` file.

**Comment by geemus** [comment]
@fblundun Could you share the rest of the related file? Nothing is jumping out at me from the narrower context here. Thanks!

**Comment by fblundun** [comment]
Here is a minimal example which errors only when run with irb:

```ruby
require 'fog'

f = Fog::Storage.new({
    :provider => 'AWS',
    :region => 'us-east-1',
    :aws_access_key_id => 'REDACTED',
    :aws_secret_access_key => 'REDACTED'
})

f.sync_clock

f.directories.get(
    'snowplow-hosted-assets',
    :prefix => '4-storage/redshift-storage/jsonpaths/com.snowplowanalytics.monitoring.batch'
)
```

**Comment by geemus** [comment]
Could you try this? I think it might eliminate a few more possibilities, and seems to be working for me:

```ruby
require 'fog'

f = Fog::Storage.new({
    :provider => 'AWS',
    :region => 'us-east-1',
    :aws_access_key_id => 'REDACTED',
    :aws_secret_access_key => 'REDACTED'
})

f.sync_clock

f.directories.all
```

**Comment by fblundun** [comment]
Your are right - changing it to `f.directories.all` does not cause an error even when executing the file with irb.

**Comment by geemus** [comment]
Hmm, is it possible the requested directory is in a region other than `us-east-1`?

**Comment by fblundun** [comment]
I just checked and the snowplow-hosted-assets bucket is actually in eu-west-1, but changing the `:region` key to "eu-west-1" doesn't prevent the error.

We have a copy in us-east-1 named "snowplow-hosted-assets-us-east-1" instead of "snowplow-hosted-assets", but making that change also doesn't prevent the error.

**Comment by geemus** [comment]
Beyond that I'm not sure what else it could be, I would expect irb to work the same as other usage (just as I presume you would expect).
