### ISSUE TITLE
InvalidClientTokenId => The security token included in the request is invalid

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-aws#21]
Original issue at: fog/fog#3387

Using fog/1.26.0 fog-core/1.27.2

```
>> iam = Fog::AWS::IAM.new(Fog.credentials)
#<Fog::AWS::IAM::Real:70166177964140 @use_iam_profile=nil @connection_options={:debug_response=>true, :headers=>{"User-Agent"=>"fog/1.26.0 fog-core/1.27.2"}, :persistent=>false} @instrumentor=nil @instrumentor_name="fog.aws.iam" @host="iam.amazonaws.com" @path="/" @persistent=false @port=443 @scheme="https" @connection=#<Fog::XML::Connection:0x007fa1ac39dd48 @excon=#<Excon::Connection:7fa1ac397bc8 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.26.0 fog-core/1.27.2"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.42.1 (x86_64-darwin14.0) ruby/2.1.5", :write_timeout=>60, :host=>"iam.amazonaws.com", :path=>"/", :port=>443, :query=>nil, :scheme=>"https"} @socket_key="https://iam.amazonaws.com:443">> @aws_session_token=nil @aws_credentials_expire_at=nil @signer=#<Fog::AWS::SignatureV4:0x007fa1ac397790 @region="us-east-1", @service="iam", @aws_access_key_id="XXX", @hmac=#<Fog::HMAC:0x007fa1ac3976f0 @key="XXX", @digest=#<OpenSSL::Digest: XXX>, @signer=#<Proc:0x007fa1ac397650@/Users/drnic/.rvm/gems/ruby-2.1.5/gems/fog-core-1.27.2/lib/fog/core/hmac.rb:28 (lambda)>>>>

>> iam.list_account_aliases
Fog::AWS::IAM::Error: InvalidClientTokenId => The security token included in the request is invalid.
    from /Users/drnic/.rvm/gems/ruby-2.1.5/gems/excon-0.42.1/lib/excon/middlewares/expects.rb:6:in `response_call'
    from /Users/drnic/.rvm/gems/ruby-2.1.5/gems/excon-0.42.1/lib/excon/middlewares/response_parser.rb:8:in `response_call'
```

**Comment by plribeiro3000** [comment]
cc/ @drnic @fcheung

**Comment by mg03** [comment]
Hi

I am facing the same issue. Both on iam as well as route53 calls. Any idea on when this can be fixed?

Regards

**Comment by lanej** [comment]
it takes some time for recently created credentials to be accepted system wide.  I would suggest that any recently cut access keys go through a wait_for loop to check that amazon's data is consistent.  

something like:
```ruby
     Fog.wait_for(self.class.validation_timeout, self.class.validation_interval) do
        begin
          user = authorization.users.current
        rescue Exception => e
          again = e.message.match(/^(AccessDenied|InvalidClientTokenId)/) ||
            e.is_a?(Excon::Errors::Timeout)
          fatal = e.message.match(/^SignatureDoesNotMatch/) # definitely not valid

          if fatal && !again
            raise
          end
        end
     end
````

**Comment by VishalBendre** [comment]
I am facing this issue for old credentials:

I was trying create new user using old default credentials:
it throws :Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: 6d3c3659-5d78-11e6-9641-1d8fe203241d

**Comment by VishalBendre** [comment]
Please help me to resolve this case
