### ISSUE TITLE
InvalidParameterCombination => You cannot move a DB instance with Single-Az enabled to a VPC (Fog::AWS::RDS::Error)

### ISSUE THREAD

**Issue by carolfly86** [fog/fog-aws#255]
Hi, 
I'm seeing this issue using modify_db_instance to modify the VpcSecurityGroups of rds instance in VPC. Though I can modify the security group from UI. Below is the option parameter I used

``` ruby
{"AllocatedStorage"=>100,
 "AutoMinorVersionUpgrade"=>true,
 "BackupRetentionPeriod"=>0,
 "DBInstanceClass"=>"db.t2.medium",
 "DBSubnetGroupName"=>"xxx",
 "Engine"=>"postgres",
 "EngineVersion"=>"9.3.6",
 "Port"=>5432,
 "VpcSecurityGroups.member.1"=>"xxx",
 "MultiAZ"=>false,
 "PreferredBackupWindow"=>"01:00-01:30",
 "PreferredMaintenanceWindow"=>"tue:02:00-tue:02:30",
 "MasterUsername"=>"xxx",
 "Memory"=>4,
 "Family"=>"postgres9.3",
 "StorageType"=>"gp2",
 "DBName"=>nil,
 "ApplyImmediately"=>true}
```

```
/.rvm/gems/ruby-2.2.1/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call': InvalidParameterCombination => You cannot move a DB instance with Single-Az enabled to a VPC (Fog::AWS::RDS::Error)
    from /.rvm/gems/ruby-2.2.1/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
    from /.rvm/gems/ruby-2.2.1/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
    from /.rvm/gems/ruby-2.2.1/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
    from /.rvm/gems/ruby-2.2.1/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
    from /.rvm/gems/ruby-2.2.1/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
    from /.rvm/gems/ruby-2.2.1/gems/fog-aws-0.9.2/lib/fog/aws/rds.rb:278:in `_request'
    from /.rvm/gems/ruby-2.2.1/gems/fog-aws-0.9.2/lib/fog/aws/rds.rb:273:in `request'
    from /.rvm/gems/ruby-2.2.1/gems/fog-aws-0.9.2/lib/fog/aws/requests/rds/modify_db_instance.rb:39:in `modify_db_instance'
```

Is there any limitation on using modify_db_instance or is it something missing in my option?

**Comment by lanej** [comment]
@carolfly86 the error message would seem to indicate that the rds instance must first be converted to `"MutliAZ" => true` before moving to a VPC security group.
