### ISSUE TITLE
NoMethodError - undefined method `signature_parameters' for nil:NilClass

### ISSUE THREAD

**Issue by andrewmcnamara** [fog/fog-aws#28]
We are having problems when uploading files to aws s3 storage using carrierwave and fog with the setting aws_signature_version set to 2. 

Specifically when we try to read the url of the downloaded file   e.g.
```ruby
class Attachment < ActiveRecord::Base
  mount_uploader :file, CarrierWave::Uploader::Base
end
attachment.file.url
```
Carrierwave config 
```ruby
  CarrierWave.configure do |config|
    config.storage = :fog
    config.fog_credentials = {
      :provider => 'AWS',
      :aws_access_key_id => '',
      :aws_secret_access_key => '',
      :aws_signature_version => 2, 
      :host => '',
    }
    config.fog_public = false
    config.fog_attributes = { 'Cache-Control' => "max-age=#{365.day.to_i}" }
  end
```

Following is the backtrace:
```
NoMethodError - undefined method `signature_parameters' for nil:NilClass:
  fog-aws (0.0.6) lib/fog/aws/storage.rb:160:in `signed_url'
  fog-aws (0.0.6) lib/fog/aws/requests/storage/get_object_url.rb:12:in `get_object_url'
  fog-aws (0.0.6) lib/fog/aws/models/storage/files.rb:82:in `get_url'
  fog-aws (0.0.6) lib/fog/aws/models/storage/file.rb:227:in `url'
  carrierwave (0.10.0) lib/carrierwave/storage/fog.rb:145:in `authenticated_url'
  carrierwave (0.10.0) lib/carrierwave/storage/fog.rb:325:in `url'
  carrierwave (0.10.0) lib/carrierwave/uploader/url.rb:20:in `url'
  carrierwave (0.10.0) lib/carrierwave/uploader/versions.rb:207:in `url'
  carrierwave (0.10.0) lib/carrierwave/uploader/default_url.rb:8:in `url'
```

**Comment by geemus** [comment]
Hmm. Perhaps we broke that edge case when we introduced the v4 signature stuff. Is there a reason you are opting for v2 instead of v4 here?

**Comment by andrewmcnamara** [comment]
We need to use v2 rather than v4 as we are using an S3 clone that does not support V4.

**Comment by fcheung** [comment]
Ah, I think that is me forgetting to add back the V2 stuff when we added the option to use V2 signatures. I will have a look this evening. Shouldn't be rocket science though
