### ISSUE TITLE
Write timeout trying to upload a large file to S3

### ISSUE THREAD

**Issue by dblessing** [fog/fog-aws#291]
`fog-aws` - 0.9.2
`fog-core` - 1.27

One of our users is having problems uploading a large (5+GB) file to S3. The process seems to be going OK but sometime after an hour the stack below is thrown. The two interesting errors I get out of it are
`Excon::Errors::Timeout: write timeout reached` and `OpenSSL::SSL::SSLErrorWaitWritable: write would block`. We've tried different `multipart_chunk_size` to no avail. I'm hoping someone here has some ideas because I've been banging my head against the wall trying to figure out what's going on. 
Thank you for your help. 

```
Excon::Errors::Timeout: write timeout reached
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:266:in `select_with_timeout'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:230:in `rescue in block in write_nonblock'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:214:in `block in write_nonblock'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:212:in `loop'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:212:in `write_nonblock'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:70:in `write'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:183:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/mock.rb:47:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/instrumentor.rb:25:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:250:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-core-1.40.0/lib/fog/core/connection.rb:81:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/storage.rb:611:in `_request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/storage.rb:606:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/models/storage/file.rb:268:in `multipart_save'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/models/storage/file.rb:209:in `save'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:51:in `create'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/manager.rb:51:in `upload'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/manager.rb:36:in `block in pack'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/manager.rb:19:in `chdir'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/manager.rb:19:in `pack'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:21:in `block (3 levels) in <top (required)>'
OpenSSL::SSL::SSLErrorWaitWritable: write would block
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:217:in `block in write_nonblock'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:212:in `loop'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:212:in `write_nonblock'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/socket.rb:70:in `write'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:183:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/mock.rb:47:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/instrumentor.rb:25:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:250:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:273:in `rescue in request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/excon-0.49.0/lib/excon/connection.rb:221:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-core-1.40.0/lib/fog/core/connection.rb:81:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/storage.rb:611:in `_request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/storage.rb:606:in `request'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/models/storage/file.rb:268:in `multipart_save'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-aws-0.9.2/lib/fog/aws/models/storage/file.rb:209:in `save'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/fog-core-1.40.0/lib/fog/core/collection.rb:51:in `create'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/manager.rb:51:in `upload'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/manager.rb:36:in `block in pack'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/manager.rb:19:in `chdir'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/manager.rb:19:in `pack'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:21:in `block (3 levels) in <top (required)>'
```

We are using multipart upload and our implementation looks like:

``` ruby
tar_file = '/path/to/5gb/file.tar'
connection_settings = {
  :provider=>"AWS",
  :region=>"us-west-2",
  :aws_access_key_id=>"secret",
  :aws_secret_access_key=>"super_secret"
}

connection = ::Fog::Storage.new(connection_settings)
directory = connection.directories.get('my_s3_bucket')

directory.files.create(key: tar_file, body: File.open(tar_file), public: false, multipart_chunk_size: 104857600)
```

**Comment by geemus** [comment]
You can pass a `:connection_options` hash inside the settings you are passing to configure some additional things. In particular, you could try extending the write timeout (defaults to 60) with `:write_timeout => 360`,  and/or setting `:nonblock => false`. Additionally, the connection has it's own chunk settings, distinct from the multipart one you mentioned, which can be set with `:chunk_size => ...` in the options described above. This one defaults to 1048576, ie 1MB.

I imagine some combination of these settings should get you what you need, but it's hard to say in the abstract which ones (and they have some tradeoffs). Hope that helps, but let me know if you have further questions or are unable to see improvement with these tweaks.

**Comment by gpapin** [comment]
@dblessing did you fixed it at the end ? Because I get the exact same error when performing a gitlab backup to S3.

**Comment by kelynch** [comment]
@dblessing Echoing the question -- I'm getting the same exact error when transferring a large-ish archive to Glacier.

**Comment by geemus** [comment]
Having not run into this myself, I'm afraid I don't have anything better to offer than before (possibly tweaking timeout settings to help).

**Comment by kelynch** [comment]
Thanks for the swift reply!  I was able to resolve this by tweaking the connection settings as follows:

```ruby
:connection_options => { :write_timeout => 3600, :nonblock => false, :chunk_size => 4194304 }
```

**Comment by geemus** [comment]
@kelynch nice, glad to hear that fixed it for you!

**Comment by WalkerFifth** [comment]
@kelynch 
Hi Miss Kelynch.
I'm new on Gitlab and I'm facing the same issue of 
this topic.
I want to try set up as bellow but, could you tell 
me where should configure it, please.
Its on /etc/gitlab/gitlab.rb file?
Thank you in advance.
