### ISSUE TITLE
"Fog::DNS[:aws] | change_resource_record_sets (aws, dns)" test suite flaky

### ISSUE THREAD

**Issue by voxik** [fog/fog-aws#301]
From time to time, I observer the following test failures on Fedora CI [1]:

```
  Fog::DNS[:aws] | change_resource_record_sets (aws, dns)
    success
      - #elb_hosted_zone_mapping from DNS name
      undefined method `hosted_zone_for_alias_target' for Fog::DNS::AWS:Class (NoMethodError)
        tests/requests/dns/change_resource_record_sets_tests.rb:4:in `block (3 levels) in <top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:140:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:140:in `assert'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:116:in `test'
        tests/requests/dns/change_resource_record_sets_tests.rb:3:in `block (2 levels) in <top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        tests/requests/dns/change_resource_record_sets_tests.rb:2:in `block in <top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
        tests/requests/dns/change_resource_record_sets_tests.rb:1:in `<top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'
    #change_resource_record_sets_data formats geolocation properly
      undefined method `change_resource_record_sets_data' for Fog::DNS::AWS:Class (NoMethodError)
        tests/requests/dns/change_resource_record_sets_tests.rb:21:in `block (2 levels) in <top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        tests/requests/dns/change_resource_record_sets_tests.rb:9:in `block in <top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
        tests/requests/dns/change_resource_record_sets_tests.rb:1:in `<top (required)>'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
        /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'
```

[1] https://apps.fedoraproject.org/koschei/package/rubygem-fog-aws

**Comment by geemus** [comment]
Strange. Some kind of require/auto-load related race condition perhaps?

**Comment by voxik** [comment]
Testing with 3.3.0, this is still an issue. Although now, trying to update the Fedora package, I hit the issue every time. But I would swear that when I started to play with 3.3.0, it was passing. I don't understand this :/

Is it actually supposed to be autoloaded? Does this \[[1]\] line imply the autoloading?

Going to workaround it for now:

~~~
sed -i "1i require 'fog/aws/requests/dns/change_resource_record_sets'\n" tests/requests/dns/change_resource_record_sets_tests.rb
~~~

[1]: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/dns.rb#L24

**Comment by geemus** [comment]
Yes, I think that should be where the require would come from.

The request should add itself to the list here: https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L202. Then when you call `new` to instantiate a service it should call out to require all the files in that list: https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L298

So it isn't exactly autoloading per se (as it happens at runtime when you create the service). It's kind of weird and at least partly there due to historical reasons, but I fear it might be painful to remove at the moment.

Hope that provides a bit more clarity as to what is supposed to happen, I am just as puzzled as you as to why it isn't actually working out that way for you though...
