### ISSUE TITLE
`NameError: uninitialized constant Fog::ServicesMixin` when requiring `fog/storage`

### ISSUE THREAD

**Issue by kjvarga** [fog/fog-aws#345]
When using the `fog-aws` gem there is an error coming from `fog-core` that a constant is not recognized.  I'm not sure who's responsible for making sure that the particular constant is defined.  But it would appear that `fog-aws` is somehow not requiring `fog/core` properly, because `fog/core.rb` *should* require `fog/core/services_mixin.rb` but that's not happening.

This is with `fog-aws` v1.2.0.

```bash
irb(main):003:0> require 'fog'
LoadError: cannot load such file -- fog
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):3
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/bin/irb:12:in `<main>'
irb(main):004:0> require 'fog/storage'
NameError: uninitialized constant Fog::ServicesMixin
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/fog-core-1.43.0/lib/fog/storage.rb:3:in `<module:Storage>'
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/fog-core-1.43.0/lib/fog/storage.rb:2:in `<module:Fog>'
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/fog-core-1.43.0/lib/fog/storage.rb:1:in `<top (required)>'
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):4
	from /Users/kvarga/.rbenv/versions/1.9.3-p484/bin/irb:12:in `<main>'
```

**Comment by geemus** [comment]
Curious. @lanej have you seen any other instances of this? I'm not sure what would have changed to break it... Thanks!
