### ISSUE TITLE
Stack Level Too Deep on YAML Serialization

### ISSUE THREAD

**Issue by CodingAnarchy** [fog/fog-aws#385]
PaperTrail is serializing the uploaded file (using CarrierWave) to YAML when the record is updated and the result is an infinite loop.  Specifically, `fog-aws` is causing a crash when it iterates through files:

```ruby
alias_method :each_file_this_page, :each
        def each
          if !block_given?
            self
          else
            subset = dup.all

            subset.each_file_this_page {|f| yield f}
            while subset.is_truncated
              subset = subset.all(:marker => subset.last.key)
              subset.each_file_this_page {|f| yield f} <- infinite recursion is here
            end

            self
          end
        end
```

This recurses until Ruby crashes on the stack level too deep error.

If it matters, the Ruby version is 2.4.1.  There should only be one image file associated with the model that Paper Trail is saving a version of.

`fog-aws` version: 1.4.0
`paper_trail` version: 7.1.0

**Comment by CodingAnarchy** [comment]
I have a workaround for now with `has_paper_trail skip: [:image]`, but the underlying issue should probably still be addressed.

**Comment by geemus** [comment]
Hmm. I don't think the YAML serialization should be particularly impactful. The point you call out for recursion is related to reading back files from s3, rather than uploading them, which also makes me less sure about how this interaction is happening. Does the paper_trail call you make there just NOT upload the image? Sorry I'm not able to be more directly helpful, but it may make more sense for you to ask on the papertrail repo as it's not clear to me this is a bug in fog. Does that make sense?

**Comment by tomgi** [comment]
I have encountered the same problem. 
It seems to be connected with using `config.cache_storage = :fog` and `paper_trail`. 
With local `cache_storage` it's working just fine.

This is the repeating part of the stack trace:
```
fog-aws (1.4.1) lib/fog/aws/models/storage/files.rb:49:in `block in each'
fog-core (1.45.0) lib/fog/core/collection.rb:18:in `each'
fog-core (1.45.0) lib/fog/core/collection.rb:18:in `each'
fog-aws (1.4.1) lib/fog/aws/models/storage/files.rb:49:in `each'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:465:in `visit_array_subclass'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:410:in `visit_Array'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:593:in `block in dump_ivars'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:591:in `each'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:591:in `dump_ivars'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:190:in `visit_Object'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:465:in `block in visit_array_subclass'
fog-aws (1.4.1) lib/fog/aws/models/storage/files.rb:49:in `block in each'
fog-core (1.45.0) lib/fog/core/collection.rb:18:in `each'
fog-core (1.45.0) lib/fog/core/collection.rb:18:in `each'
fog-aws (1.4.1) lib/fog/aws/models/storage/files.rb:49:in `each'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:465:in `visit_array_subclass'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:410:in `visit_Array'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:593:in `block in dump_ivars'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:591:in `each'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:591:in `dump_ivars'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:190:in `visit_Object'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:593:in `block in dump_ivars'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:591:in `each'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:591:in `dump_ivars'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:190:in `visit_Object'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:593:in `block in dump_ivars'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:591:in `each'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:591:in `dump_ivars'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:190:in `visit_Object'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:407:in `block in visit_Array'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:407:in `each'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:407:in `visit_Array'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:385:in `block in visit_Hash'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:383:in `each'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:383:in `visit_Hash'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:163:in `accept'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych/visitors/yaml_tree.rb:127:in `push'
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:416:in `dump'
paper_trail (7.1.1) lib/paper_trail/serializers/yaml.rb:14:in `dump'
paper_trail (7.1.1) lib/paper_trail/record_trail.rb:328:in `recordable_object_changes'
paper_trail (7.1.1) lib/paper_trail/record_trail.rb:228:in `data_for_create'
paper_trail (7.1.1) lib/paper_trail/record_trail.rb:210:in `record_create'
paper_trail (7.1.1) lib/paper_trail/model_config.rb:35:in `block in on_create'
```

**Comment by tomgi** [comment]
It seems to be connected with this issue - https://github.com/airblade/paper_trail/issues/134
`paper_trail` tries to serialize the whole model to yaml including the underlying uploader with AWS connection, etc.
It's working with local `cache_storage` however so I don't really know in which gem this issue should be posted.

**Comment by geemus** [comment]
Thanks for the additional detail. It sounds more like an issue with how paper_trail tries to serialize the uploader than an issue with the uploader itself. As such, it would probably make sense to report it over there instead. That said, in the linked issue it suggests a `:skip` option that might be helpful? ie maybe you can skip the uploader in the serialization and be good-to-go? In any event, I'm afraid it sounds more like a paperclip issue than fog. So I'm happy to discuss further, but my advise is likely to become pretty speculative.
