### ISSUE TITLE
Accessing AWS S3 using EC2 Instance Profile

### ISSUE THREAD

**Issue by suketng** [fog/fog-aws#423]
Hi,

Can you please help me with the code to use to access AWS S3 using the EC2 Instance Profile ? I do not want to use Access Key/Secret Key to access AWS S3.

**Comment by geemus** [comment]
What have you tried so far? What issues are you seeing?

**Comment by davewalter** [comment]
Hi @geemus,

We've been struggling with this same issue recently. So far, we have tried 3 possible configurations.

The first configuration completely omitted the aws_access_key_id and aws_secret_access_key options, and resulted in the following error:

```
ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/core/service.rb:244:in `validate_options'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/core/service.rb:268:in `handle_settings'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/core/service.rb:98:in `new'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/core/services_mixin.rb:16:in `new'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/storage.rb:27:in `new'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:194:in `connection'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:184:in `directory'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:180:in `dir'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:130:in `files'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:176:in `file'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:40:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:25:in `block in exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:139:in `with_retries'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:20:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:23:in `block in exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:61:in `error_handling'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:23:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:16:in `upload_buildpack'
```
The second configuration included those keys, but with values of empty string. This resulted in the following error:

```
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.</Message><RequestId>REQUESTID</RequestId><HostId>HostID</HostId></Error>"
  :cookies       => [
  ]
  :headers       => {
    "Connection"          => "close"
    "Content-Type"        => "application/xml"
    "Date"                => "Tue, 20 Feb 2018 18:56:53 GMT"
    "Server"              => "AmazonS3"
    "x-amz-bucket-region" => "us-west-2"
    "x-amz-id-2"          => "HostID"
    "x-amz-request-id"    => "REQUESTID"
  }
  :host          => "s3-us-west-2.amazonaws.com"
  :local_address => "10.0.4.12"
  :local_port    => 58252
  :path          => "/my-bucket/"
  :port          => 443
  :reason_phrase => "Bad Request"
  :remote_ip     => "x.x.x.x"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:414:in `response'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:263:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-xml-0.1.3/lib/fog/xml/sax_parser_connection.rb:35:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:7:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-aws-1.4.1/lib/fog/aws/storage.rb:612:in `_request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-aws-1.4.1/lib/fog/aws/storage.rb:607:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-aws-1.4.1/lib/fog/aws/requests/storage/get_bucket.rb:43:in `get_bucket'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-aws-1.4.1/lib/fog/aws/models/storage/directories.rb:21:in `get'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/directory.rb:16:in `get'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/idempotent_directory.rb:10:in `get_or_create'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:180:in `dir'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:130:in `files'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:176:in `file'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:40:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:25:in `block in exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:139:in `with_retries'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:20:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:23:in `block in exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:61:in `error_handling'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:23:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:16:in `upload_buildpack'
```
The last configuration included the keys with bogus values. This resulted in the following error:
```
Excon::Error::Forbidden: Expected(200) <=> Actual(403 Forbidden)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>foo</AWSAccessKeyId><RequestId>REQUESTID</RequestId><HostId>HostID</HostId></Error>"
  :cookies       => [
  ]
  :headers       => {
    "Content-Type"        => "application/xml"
    "Date"                => "Fri, 16 Feb 2018 22:20:08 GMT"
    "Server"              => "AmazonS3"
    "x-amz-bucket-region" => "us-west-2"
    "x-amz-id-2"          => "HostID"
    "x-amz-request-id"    => "REQUESTID"
  }
  :host          => "s3-us-west-2.amazonaws.com"
  :local_address => "10.0.4.12"
  :local_port    => 43396
  :path          => "/my-bucket/"
  :port          => 443
  :reason_phrase => "Forbidden"
  :remote_ip     => "x.x.x.x"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:414:in `response'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:263:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/base.rb:11:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/base.rb:11:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:283:in `rescue in request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:226:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/base.rb:11:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/base.rb:11:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:283:in `rescue in request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:226:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/idempotent.rb:33:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/base.rb:11:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/middlewares/base.rb:11:in `error_call'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:283:in `rescue in request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon/connection.rb:226:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-xml-0.1.3/lib/fog/xml/sax_parser_connection.rb:35:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:7:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-aws-1.4.1/lib/fog/aws/storage.rb:612:in `_request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-aws-1.4.1/lib/fog/aws/storage.rb:607:in `request'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-aws-1.4.1/lib/fog/aws/requests/storage/get_bucket.rb:43:in `get_bucket'
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/fog-aws-1.4.1/lib/fog/aws/models/storage/directories.rb:21:in `get'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/directory.rb:16:in `get'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/idempotent_directory.rb:10:in `get_or_create'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:180:in `dir'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:130:in `files'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:176:in `file'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/fog_client.rb:40:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:25:in `block in exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:139:in `with_retries'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/retryable_client.rb:20:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:23:in `block in exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:61:in `error_handling'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/blobstore/fog/error_handling_client.rb:23:in `exists?'
/var/vcap/data/packages/cloud_controller_ng/tmp/cloud_controller_ng/lib/cloud_controller/upload_buildpack.rb:16:in `upload_buildpack'
```
For reference, we have confirmed that the appropriate IAM instance profile is associated with the VM under test (in the AWS console), and have verified (by use of the aws cli) that we can successfully access the contents of the desired bucket.

Any help that you can provide would be greatly appreciated!

Thanks,
Dave and @kkallday

**Comment by geemus** [comment]
I believe to use iam instance profile you simply pass credentials like:

```
{ use_iam_profile: true }
```

When this is set, the [credential fetcher](https://github.com/fog/fog-aws/blob/1caf487df8fcedb949ec6d5c2dbf7721d2b1a65d/lib/fog/aws/credential_fetcher.rb#L16) should make the appropriate local calls and fill in the other credentials on your behalf (so you shouldn't have to set any other keys).

Note, I'm just referring to docs/tests for this and haven't tried it directly (don't really have AWS stuff setup to easily test at present). Hopefully that gets you back on track though, we should probably think about adding this more explicitly to the docs, as it is clearly a point of some confusion.

Could you give that a try and see if you have better luck? Thanks!

**Comment by davewalter** [comment]
All of the attempts had that config option set to true. The first one completely omitted the AWS access key ID/secret, which I think matches what you are suggesting. However, that hits the method option validation here: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/storage.rb#L44

**Comment by geemus** [comment]
Hmm, I'm not sure beyond that (as I think this was submitted/tested by other contributors instead of me directly).

@lanej any chance you have more direct insights you could share? Thanks!

**Comment by lanej** [comment]
@davewalter it would be helpful if we could see how you initialize the client.  

Please provide the output when using:

```
Excon.defaults.merge!(:debug_request => true, :debug_response => true)
```

we should see a request issued against the internal metadata endpoint (don't forget to scrubs secrets)

**Comment by geemus** [comment]
@davewalter Hey, to follow up, I've been digging into this more. I believe passing just `use_iam_profile: true` is the expected usage after all. I'm not certain why it isn't currently working, but maybe you can help us narrow down options. Could you try the suggested methods here to make sure outside of fog your EC2 setup is working as expected? https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_iam-ec2.html#troubleshoot_iam-ec2_no-keys

Thanks!

**Comment by davewalter** [comment]
Hi @geemus,

It will take a little time to get an environment set up to test this, but I did note in my original comment that "For reference, we have confirmed that the appropriate IAM instance profile is associated with the VM under test (in the AWS console), and have verified (by use of the aws cli) that we can successfully access the contents of the desired bucket."

The hard part is that I am not on the team that maintains the code that uses the fog gem directly. I am on a team that consumes the code that uses the fog gem, so my understanding of how they use it and my ability to debug is limited. I will try to engage the appropriate people to help get answers to your questions.

Regards,
Dave

**Comment by geemus** [comment]
@davewalter thanks for the update, sorry I overlooked the instance profile details in the original post. Do let me know if you have further questions or I can help, though it does sound like it may be a little awkward to get all the dots connected.

**Comment by ctavplay** [comment]
I thought we were being burned by this until I tried using access keys to upload to S3.  That's when I realized that we're going through our HTTP proxy to reach the bucket and not our S3 VPC endpoint, which made me think that perhaps our proxy settings were incorrect.  If you have configured the `http_proxy` and `https_proxy` environment variables without specifying the metadata endpoint (169.254.169.254) in the `no_proxy` environment variable then fog can't use the instance profile credentials.  The real bug here is that fog's error messages are not indicative of this.  If `use_iam_profile` is set to true and connecting to 169.254.169.254 results in an error it should probably output an error message then. I hope that helps @geemus @davewalter?

**Comment by geemus** [comment]
Thanks for the detailed report! I'd welcome help on improving the error messages if you get a chance.

**Comment by richddr** [comment]
@geemus is there any update on fixing this?

**Comment by geemus** [comment]
@richddr no news I'm afraid, as I haven't had any additional data to work with. Could you perhaps try running after setting:

`Excon.defaults.merge!(:debug_request => true, :debug_response => true)`

And let us know what you get (be sure to scrub secrets), this may help us narrow down the culprit. Thanks.
