### ISSUE TITLE
Undefined method `change_resource_record_sets_data' for Fog::AWS:Module called from fog/aws/requests/dns/change_resource_record_sets.rb when attempting to modify a DNS record.

### ISSUE THREAD

**Issue by klarrimore** [fog/fog-aws#477]
I'm running into an issue with both ruby 2.4.0 and 2.3.3.

**issue.rb**
```ruby
#!/usr/bin/env ruby

require 'bundler/setup'
require './lib/fog-aws'

options = {
  :provider => 'AWS',
  :aws_access_key_id => '<key-id>',
  :aws_secret_access_key => '<access-key>'
}

dns = Fog::DNS.new(options)

zone = dns.zones.get '<zone-id>'
record = zone.records.select { |record| record.name == 'example.com.' }.first
record.modify(:value => "fail.example.com.")
```
**output**
```
ruby issue.rb
/home/klarrimore/Projects/fog-aws/lib/fog/aws/requests/dns/change_resource_record_sets.rb:197:in `change_resource_record_sets': undefined method `change_resource_record_sets_data' for Fog::AWS:Module (NoMethodError)
        from /home/klarrimore/Projects/fog-aws/lib/fog/aws/models/dns/record.rb:59:in `modify'
        from issue.rb:17:in `<main>'
```
**fix - change line 197 in change_resource_record_sets.rb to the following**
```ruby
body = Fog::AWS::DNS.change_resource_record_sets_data(zone_id, change_batch, @version, options)
```

**Comment by geemus** [comment]
Thanks for the detailed report and fix!

**Comment by mattheworiordan** [comment]
Hey @geemus. I keep hitting this bug  as the latest stable release is still 3.3.0 which contains this bug.  Any chance you could bump the version as I'm always a bit nervous about locking into an unreleased version of a Gem we depend on.  Shout out if I can help.

**Comment by geemus** [comment]
Sure thing, thanks for the nudge. Should be out as part of v3.4.0
