### ISSUE TITLE
Lambda Parser can't handle VPC config, containing array of hash values

### ISSUE THREAD

**Issue by nc-augerk** [fog/fog-aws#509]
We created a Lambda function with VPC configuration. When attempting to `list_functions` an error is thrown:
```
Traceback (most recent call last):
       16: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:17:in `rules'
       15: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:17:in `map'
       14: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:17:in `block in rules'
       13: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `process'
       12: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `inject'
       11: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `each'
       10: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `block in process'
        9: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:15:in `rules'
        8: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `process'
        7: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `inject'
        6: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `each'
        5: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `block in process'
        4: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:17:in `rules'
        3: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:17:in `map'
        2: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:17:in `block in rules'
        1: from /var/www/likeassets/current/vendor/cache/ruby/2.5.0/gems/fog-aws-2.0.0/lib/fog/aws/parsers/lambda/base.rb:7:in `process'
NoMethodError (undefined method `inject' for "sg-0a1b2c3d4e5f":String)
```
Using a one-to-one parser the response looked something like this:
```
{
        "CodeSha256"=>"shashashashashashashashasha",
        "CodeSize"=>646,
        "DeadLetterConfig"=>nil,
        "Description"=>"",
        "Environment"=>nil,
        "FunctionArn"=>
         "arn:aws:lambda:us-east-1:123456789012:function:myFunction",
        "FunctionName"=>"myFunction",
        "Handler"=>"lambda_function.lambda_handler",
        "KMSKeyArn"=>nil,
        "LastModified"=>"2019-03-10T02:38:24.394+0000",
        "Layers"=>nil,
        "MasterArn"=>nil,
        "MemorySize"=>128,
        "RevisionId"=>"some-revision-id",
        "Role"=>"arn:aws:iam::123456789012:role/myRole",
        "Runtime"=>"ruby2.5",
        "Timeout"=>3,
        "TracingConfig"=>{"Mode"=>"PassThrough"},
        "Version"=>"$LATEST",
        "VpcConfig"=> {
           "SecurityGroupIds"=>["sg-0a1b2c3d4e5f"],
           "SubnetIds"=>[
             "subnet-0a1b2c3d4e5f1",
             "subnet-0a1b2c3d4e5f2",
             "subnet-0a1b2c3d4e5f3"
           ],
           "VpcId"=>"vpc-0a1b2c3d4e5f4",
           "VpcSetupStatus"=>nil,
           "VpcSetupStatusReason"=>nil
         }
},
```
Notice the `SecurityGroupIds` and `SubnetIds` use arrays of strings. [Here](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/parsers/lambda/base.rb#L17) the processor attempts to further process those strings and fails to `inject` them.

**Comment by geemus** [comment]
Thanks for the detailed report. I guess we might need to sub-divide the Array case, processing if the elements are themselves Hash objects, but simply returning otherwise? Does that sound right to you? Would you be willing to help with a patch? Thanks!

**Comment by nc-augerk** [comment]
That sounds like it'll work. As much as I would like to help, I'm afraid we're not yet in a place that we can devote time to giving back to the community. Here's a parser I built to work around the issue, if anyone else needs help.
```
require "fog/aws/parsers/lambda/base"

module Aws
  class LambdaParser < Fog::AWS::Parsers::Lambda::Base
    # Patch for the Fog Parser that has an issue processing arrays of strings
    # Arrays of strings are found in VPC config for Lambda functions
    def process(body)
      body.is_a?(String) ? body : super(body)
    end
  end
end
```
I suppose we could have also inverted it to check if the body was a Hash.
